# @(#) %full_filespec: expert_descrip_user.make~15:makefile:EXP#1 %
#=========================================================================#
#                                                                         #
#  
#                                                                         #
#=========================================================================#

help ::
	@echo ""
	@echo "under root, make -f expert_descrip_user.make target ..."
	@echo ""
	@echo "           help      ==> to display this help"
	@echo ""
	@echo "$(EXPERT_EXECUTABLE) ==> to generate the $(EXPERT_EXECUTABLE) executable"
	@echo ""
	@echo "           clean     ==> to clean files associated to the generated $(EXPERT_EXECUTABLE) "
	@echo ""
	@echo "           new_appli ==> to update dictionary, enroll the new management module, and create the application"
	@echo ""
	@echo "           clean_fm  ==> to clean dictionary, disenroll the mm, and delete the application"
	@echo ""
	@echo "           kit       ==> to generate a loadable run time kit that will package $(EXPERT_EXECUTABLE)"
	@echo ""


#=========================================================================#
#                                                                         #
# MM Variables                                                            #
#                                                                         #
#=========================================================================#

# IDs number 492 and 493 may be used for testing purpose
USER_EXPERT_FM_NEW_ID = 1258

# associated MM names are user1_expert_fm and user2_expert_fm
USER_EXPERT_FM_NEW_NAME = LAB_EXPERT

USER_EXPERT_FM_NEW_EXECUTABLE = temip_LAB_EXPERT_FM


#=========================================================================#
#                                                                         #
# Customization of the makefile variables                                 #
#                                                                         #
#=========================================================================#

# The name of the expert in the current directory
EXPERT_EXECUTABLE 	= $(USER_EXPERT_FM_NEW_EXECUTABLE)

# The location of the files customized relative to the 
# Build directory. It can be a relative or an absolute path but it can not
# be the shell command `pwd`.
USER_FILES_DIR 		= ..

# The name of the msl files to be used.
#MSL_FILES= 

# The name of the generated script that starts the ilog graphical builder 
ILRBUILDER_FILE = LAB_EXPERT_FM_builder.sh

# The root name of the model generated by msl2ilr, resulting in the
# compilation of the MSL_FILES
MSL_MODEL_NAME		= MSL_model

# The name of the customized builder and startup files (without extention)
STARTUP_STUB 		= exp_startup_user
BUILDER_STUB 		= exp_builder_user

#=========================================================================#
#                                                                         #
# Expert Custom variables                                                 #
#                                                                         #
#=========================================================================#

#The name of the user object model (ilr file without extension) (optional)
USER_MODEL = user_model

# STUB Files needed when specific user object model is used (without extension) (optional)
ILR_INTERFACE_STUB = exp_ilr_interface_user

# Include Dir for compiling MSL files
TEMIP_INSTALL=/usr/opt/temip
USER_MSL_INCLUDE = $(TEMIP_INSTALL)/mmtoolkit/msl

# custom option to customize TeMIPEntity used class
ENTITY_CLASS = TeMIPEntityUser

#The name of the user TeMIPEntity ilog model (ilr file without extension) (optional)
ENTITY_MODEL = temip_entity_user

#=========================================================================#
#                                                                         #
# Connection and Data Ports                                               #
#                                                                         #
#=========================================================================#

# the port number for data communication with the expert module
# this number is send by the Ilog builder to the expert module
# when connecting
DATA_PORT = 3002

# the port used by the ilog Builder to connect to the expert module.
# this number is the default value printed in the connect window
# of the Ilog Builder
ILR_DFLT_CONNECTION_PORT = 3001


#=========================================================================#
#                                                                         #
# Call to the makefile located in the Build directory with the specific   #
# files name.	                                                          #
#                                                                         #
#=========================================================================#

$(EXPERT_EXECUTABLE)::
	-(cd Build; for ii in $(MSL_FILES?$(MSL_FILES):"") $(USER_MODEL?$(USER_MODEL).ilr:"") $(ENTITY_MODEL?$(ENTITY_MODEL).ilr:"") ;\
	    do \
		if [ X$$ii != X ] ;\
		then \
			if [ -f $(USER_FILES_DIR)/$$ii ] ;\
			then \
				ln -s $(USER_FILES_DIR)/$$ii . ;\
			else \
				if [ -f $$ii ] ;\
				then ln -s $$ii . ;\
				else \
					echo "$$ii file does not exist" ;\
					exit 1 ;\
				fi ;\
			fi ;\
		fi ; \
	   done) 
	(cd Build; \
	 MSL_FILES_BASENAMED="" ;\
	 for ii in $(MSL_FILES?$(MSL_FILES):empty.ms) ;\
	 do \
		MSL_FILES_BASENAMED="$$MSL_FILES_BASENAMED `basename $$ii`" ;\
	 done ;\
	 $(MAKE) -f expert_descrip.make \
		MSL_MODEL=$(MSL_MODEL_NAME) \
		MSL_FILES="$$MSL_FILES_BASENAMED" \
		USER_FILES_DIR=$(USER_FILES_DIR) \
		USER_MODEL=`basename "$(USER_MODEL)"` \
		USER_MODEL_PACKAGE_NAME=`basename "$(USER_MODEL)"` \
		EXPERT_EXECUTABLE=$(EXPERT_EXECUTABLE) \
		ILRBUILDER_FILE=$(ILRBUILDER_FILE) \
		ILR_INTERFACE_STUB=$(ILR_INTERFACE_STUB) \
		STARTUP_STUB=$(STARTUP_STUB) \
		BUILDER_STUB=$(BUILDER_STUB) \
		MSL_INCLUDE=-I$(USER_MSL_INCLUDE) \
		DATA_PORT=$(DATA_PORT) \
		ILR_DFLT_CONNECTION_PORT=$(ILR_DFLT_CONNECTION_PORT) \
		ENTITY_CLASS=$(ENTITY_CLASS) \
		ENTITY_MODEL=$(ENTITY_MODEL) \
		ENTITY_MODEL_PACKAGE_NAME=`basename "$(ENTITY_MODEL)"` \
		entityCustomizedExpert; \
	ln -fs `pwd`/$(EXPERT_EXECUTABLE) $(USER_FILES_DIR)/$(EXPERT_EXECUTABLE) ; \
	ln -fs `pwd`/$(ILRBUILDER_FILE) $(USER_FILES_DIR)/$(ILRBUILDER_FILE) )


clean::
	-(cd Build; for ii in $(MSL_FILES?$(MSL_FILES):"") $(USER_MODEL?$(USER_MODEL).ilr:"") $(ENTITY_MODEL?$(ENTITY_MODEL).ilr:"") ;\
	   do \
		if [ X$$ii != X ] ;\
		then \
			if [ -L `basename $$ii` ] ;\
			then \
				rm -f `basename $$ii` ;\
			fi ;\
		fi ;\
	   done \
	) 
	(cd Build; \
	$(MAKE) -f expert_descrip.make clean \
		MSL_MODEL=$(MSL_MODEL_NAME) \
		MSL_FILES="$(MSL_FILES?$(MSL_FILES):empty.ms)" \
		ILRBUILDER_FILE=$(ILRBUILDER_FILE) \
		ILR_INTERFACE_STUB=$(ILR_INTERFACE_STUB) \
		USER_MODEL=$(USER_MODEL) \
		USER_FILES_DIR=$(USER_FILES_DIR) \
		EXPERT_EXECUTABLE=$(EXPERT_EXECUTABLE) \
		STARTUP_STUB=$(STARTUP_STUB) \
		BUILDER_STUB=$(BUILDER_STUB) \
		EXPERT_FM_NEW_ID=$(USER_EXPERT_FM_NEW_ID); \
	rm -f $(USER_FILES_DIR)/$(EXPERT_EXECUTABLE) ; \
	rm -f $(USER_FILES_DIR)/$(ILRBUILDER_FILE));


#=============================================#
# MM update                                   #
#=============================================#

new_appli:
	$(MAKE) -f Build/expert_descrip.make \
	EXPERT_FM_NEW_ID=$(USER_EXPERT_FM_NEW_ID) \
	EXPERT_FM_NEW_NAME=$(USER_EXPERT_FM_NEW_NAME) \
	EXPERT_FM_NEW_EXECUTABLE=$(USER_EXPERT_FM_NEW_EXECUTABLE) \
	all_new

clean_fm:
	$(MAKE) -f Build/expert_descrip.make \
	EXPERT_FM_NEW_ID=$(USER_EXPERT_FM_NEW_ID) \
	EXPERT_FM_NEW_NAME=$(USER_EXPERT_FM_NEW_NAME) \
	EXPERT_FM_NEW_EXECUTABLE=$(USER_EXPERT_FM_NEW_EXECUTABLE) \
	restaure



#=============================================#
# KIT Generation                              #
#=============================================#

# ${EXPERT_FM_NEW_EXECUTABLE} is created by default by the 
# new_appli target

include exp_version.include

kit: $(EXPERT_FM_NEW_EXECUTABLE)
	/usr/opt/temip/EXP$(EXP_VERSION)/bin/exp_create_rtkit.ksh -id $(USER_EXPERT_FM_NEW_ID) -name $(USER_EXPERT_FM_NEW_NAME) -exec $(USER_EXPERT_FM_NEW_EXECUTABLE)
